[profile.default]
src = "contracts"
out = 'out'
libs = ['lib']
solc_version = '0.8.13'
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read", path = "./"}]
gas_reports = ["*"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config