/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721ASol from "./ERC721A.sol";
export type { erc721ASol };
import type * as erc721AL2Sol from "./ERC721A_L2.sol";
export type { erc721AL2Sol };
export type { IERC721A } from "./IERC721A";
